In [ ]:
import seaborn as sns
import pandas as pd


df = sns.load_dataset('taxis');
df;

In [ ]:
from sklearn.preprocessing import LabelEncoder
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [ ]:
# remove pickup & dropoff column


df = df.drop(['pickup', 'dropoff'], axis=1)


df.head()

,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [ ]:
# import the label encoder class
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder() # creating the class

In [ ]:
df = pd.get_dummies(df,drop_first=True)

In [ ]:
def encode_dataframe(df):
  le = LabelEncoder()
  for col in df.select_dtypes(include=['object']).columns:
        df[col] = le.fit_transform(df[col].astype(str))

  return df

In [ ]:
df = encode_dataframe(df)
print(df.head())

   passengers  distance  fare   tip  tolls  total  color_yellow  \
0           1      1.60   7.0  2.15    0.0  12.95          True
1           1      0.79   5.0  0.00    0.0   9.30          True
2           1      1.37   7.5  2.36    0.0  14.16          True
3           1      7.70  27.0  6.15    0.0  36.95          True
4           3      2.16   9.0  1.10    0.0  13.40          True

   payment_credit card  pickup_zone_Alphabet City  pickup_zone_Astoria  ...  \
0                 True                      False                False  ...
1                False                      False                False  ...
2                 True                       True                False  ...
3                 True                      False                False  ...
4                 True                      False                False  ...

   dropoff_zone_World Trade Center  dropoff_zone_Yorkville East  \
0                            False                        False
1                            False                        False
2                            False                        False
3                            False                        False
4                            False                        False

   dropoff_zone_Yorkville West  pickup_borough_Brooklyn  \
0                        False                    False
1                        False                    False
2                        False                    False
3                         True                    False
4                         True                    False

   pickup_borough_Manhattan  pickup_borough_Queens  dropoff_borough_Brooklyn  \
0                      True                  False                     False
1                      True                  False                     False
2                      True                  False                     False
3                      True                  False                     False
4                      True                  False                     False

   dropoff_borough_Manhattan  dropoff_borough_Queens  \
0                       True                   False
1                       True                   False
2                       True                   False
3                       True                   False
4                       True                   False

   dropoff_borough_Staten Island
0                          False
1                          False
2                          False
3                          False
4                          False

[5 rows x 410 columns]